In [3]:
import numpy as np

In [5]:
np.__version__



'1.24.2'

In [7]:
# vector 
vector = np.array([7,3,7,23,78,3])
vector

array([ 7,  3,  7, 23, 78,  3])

In [8]:
type(vector)

numpy.ndarray

In [9]:
# its bad
for num in vector:
    print(num*2)

14
6
14
46
156
6


In [10]:
# vectorization and broadcasting
vector*2

array([ 14,   6,  14,  46, 156,   6])

In [11]:
# 2d array
matrix=np.array(
    [
        [1,2,3],
        [8,2,7],
        [9,2,6]
    ]
)

In [12]:
matrix*2

array([[ 2,  4,  6],
       [16,  4, 14],
       [18,  4, 12]])

In [13]:
for num in matrix:
    print(num*2)

[2 4 6]
[16  4 14]
[18  4 12]


In [14]:
matrix*matrix


array([[ 1,  4,  9],
       [64,  4, 49],
       [81,  4, 36]])

In [15]:
np.divide(matrix,matrix)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
matrix@matrix

array([[44, 12, 35],
       [87, 34, 80],
       [79, 34, 77]])

In [17]:
np.matmul(matrix,matrix)

array([[44, 12, 35],
       [87, 34, 80],
       [79, 34, 77]])

# # Array Type

In [18]:
np.array([5,8,9,3,7],dtype=np.int32)

array([5, 8, 9, 3, 7])

In [19]:
np.array([5,4,5,9,4],dtype=np.float64)

array([5., 4., 5., 9., 4.])

In [20]:
np.array([5,7,8,9,5],dtype=np.complex64)

array([5.+0.j, 7.+0.j, 8.+0.j, 9.+0.j, 5.+0.j], dtype=complex64)

In [21]:
np.array([5,7,8,9,5],dtype=np.str_)

array(['5', '7', '8', '9', '5'], dtype='<U1')

In [22]:
np.array([5,7,8,9,5],dtype=np.object_)

array([5, 7, 8, 9, 5], dtype=object)

## Array Inspection

In [23]:
vector=np.array([5,4,3,7,9])
vector

array([5, 4, 3, 7, 9])

In [24]:
vector.dtype

dtype('int32')

In [25]:
vector.shape

(5,)

In [26]:
matrix.shape

(3, 3)

In [27]:
vector.size

5

In [28]:
vector.ndim

1

In [29]:
vector.itemsize

4

## io

In [30]:
matrix

array([[1, 2, 3],
       [8, 2, 7],
       [9, 2, 6]])

## Saving

In [31]:
# numpy save system

In [32]:
matrix.dumps()

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x03K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i4q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X$\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x08\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00\x00\t\x00\x00\x00\x02\x00\x00\x00\x06\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [33]:
matrix.dump("matrix.npy")

In [34]:
np.save("matrix2.npy",matrix)

## Loading


In [35]:
import numpy as np

In [36]:
arr=np.load('matrix.npy',allow_pickle=True)
arr

array([[1, 2, 3],
       [8, 2, 7],
       [9, 2, 6]])

In [37]:
arr/2

array([[0.5, 1. , 1.5],
       [4. , 1. , 3.5],
       [4.5, 1. , 3. ]])

## Saving as ZIP

In [38]:
np.savez(
    'arrayZIP.npz',vector=vector,
    matrix=matrix
)

In [39]:
file=np.load('arrayZIP.npz')

In [42]:
file.files

['vector', 'matrix']

In [43]:
file['vector']

array([5, 4, 3, 7, 9])

In [44]:
file['matrix']

array([[1, 2, 3],
       [8, 2, 7],
       [9, 2, 6]])