In [2]:
import numpy as np

## Generation of Array

In [3]:
np.arange(10,26,2)

array([10, 12, 14, 16, 18, 20, 22, 24])

In [6]:
np.arange(10,26,2,dtype=np.float16)

array([10., 12., 14., 16., 18., 20., 22., 24.], dtype=float16)

In [9]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [10]:
np.logspace(0,1,10)

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

In [15]:
np.empty([2,2,3],dtype=np.float16)

array([[[4.578e-05, 0.000e+00, 0.000e+00],
        [0.000e+00, 0.000e+00, 0.000e+00]],

       [[1.080e-03, 1.325e-03, 0.000e+00],
        [0.000e+00, 2.122e-05, 3.290e-04]]], dtype=float16)

In [16]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [21]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [23]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [25]:
np.eye(6,k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.eye(6,k=-2)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [27]:
np.full([2,2],3)

array([[3, 3],
       [3, 3]])

In [28]:
def fun(r,c):
    return r*c
np.fromfunction(fun,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])